### ISSUE TITLE
Bug with add task start/end dates

### ISSUE THREAD

**Issue by DrJonnyT** [UoMResearchIT/CapX#1152]
When I make a new task with a fixed start and end date, the defaults are for today and tomorrow for the start and end. When I add a start date, I think it should update for the default end date to be something like the day after the start date. But it's still set to tomorrow. So then I end up with something like this for the start and end dates:

<img width="1619" height="418" alt="Image" src="https://github.com/user-attachments/assets/4b00e64a-dd01-49a3-8953-c2d1a9c00ded" />

If you now add a person to the task, click update and save. The default end date changes to the same as the start date, but you also get yellow bar of doom and the actuals on the task is NaN

**Comment by aharwood2** [comment]
We have been fiddling with the behaviour via #902 so it might be that this behaviour is fixed by that. Will need to look into this after that is merged to see if I can reproduce.

**Comment by DrAtbas** [comment]
@aharwood2 
It seems Jonny was right, the changes we made did not solve his issue.

The issue is being caused by Division by Zero. In the SubTask.Schedule() method is dividing it by 0 after the start, and the dates are changed.

The fixes I pushed in should help solve this issue.
