### ISSUE TITLE
Allow multiple project owners

### ISSUE THREAD

**Issue by DrJonnyT** [UoMResearchIT/CapX#540]
If you have a project with multiple tasks, where each task represents a separate chunk of work, currently there is no way for one person to own some tasks and someone else to own others. So only the owner of the main project can post status updates

**Comment by ianhinder** [comment]
I thought that only project managers could see the comments on a project?

**Comment by DrJonnyT** [comment]
Allow multiple project...managers?

**Comment by aharwood2** [comment]
All managers can see notes and post notes. I presume, Jonny, you are wanting to edit task configuration which I believe is only limited to the project owner.

**Comment by DrJonnyT** [comment]
We have resolved this as a permissions issue that is now resolved so not required. If there are any other use cases for multiple project owners I can leave this open but happy to close it now

**Comment by aharwood2** [comment]
I think let's leave it open but perhaps we can take it off the next release milestone.

**Comment by aharwood2** [comment]
Having thought about this some more, I'm still not sure we really want to have this as the single owner idea is good for accountability. I'm going to knock it back to on hold as we think about it some more.
